# Generated by Django 5.2.6 on 2025-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_link_description_link_thumbnail_url_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
