# Generated by Django 5.2.6 on 2025-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_link_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='link',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='link',
            name='video_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
    ]
