name: Django CI/CD with PythonAnywhere

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy on PythonAnywhere
        run: |
          curl -X POST \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
          https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/<your-domain>.pythonanywhere.com/reload/
